### PR TITLE
Add debian 10

### PR DESCRIPTION
**Pull request by CesarBallardini**
Add Debian 10 (Buster) to supported distros.

### CODE REVIEW

**Comment by tersmitten** [comment]
Have you tested Debian 10?

**Comment by tersmitten** [comment]
If it does work, also make sure to add it here: https://github.com/Oefenweb/ansible-locales/blob/master/meta/main.yml#L21

**Comment by CesarBallardini** [comment]
> Have you tested Debian 10?

Yes, with spanish/Argentina as default.  Also works with several locales.

**Comment by CesarBallardini** [comment]
> If it does work, also make sure to add it here: https://github.com/Oefenweb/ansible-locales/blob/master/meta/main.yml#L21

Done

**Pull request merged**
